version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_BASE: ${VITE_API_BASE:-}
    container_name: ${APP_NAME:-app}-web
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8080}:80"
    # Если у тебя есть общий reverse-proxy (Traefik/Nginx Proxy Manager),
    # лучше вместо ports подключиться к внешней сети прокси:
    # networks:
    #   - proxy

# networks:
#   proxy:
#     external: true
